DELIMITER ;
SET FOREIGN_KEY_CHECKS=0;
insert ignore into ds_pug_templates (name,id,note,template) values ('wm_berichte_tanboegen_tabelle','wm_berichte_tanboegen_tabelle',from_base64('d21fYmVyaWNodGVfdGFuYm9lZ2VuX3RhYmVsbGU='),from_base64( 'CnRhYmxlLmNhbmRpZGF0ZXRhYmxlCgl0cgogICAgCXRoLnJhbmsgTnIuCiAgICAJdGguYW56ZWln
ZV9uYW1lICZuYnNwOwogICAgLSB2YXIgbGFzdCA9IDEKCWVhY2ggcmVjb3JkIGluIGRhdGEKICAg
ICAgdHIudHJfbm90dm90ZWQKICAgICAgICB0ZC5yYW5rICF7cmVjb3JkLmlkfQogICAgICAgIHRk
CiAgICAgICAgCWJhcmNvZGVpbWFnZSh0eXBlPSJjMzkiLGRhdGE9cmVjb3JkLnRhbm51bW1lciwi
c3R5bGUiPSJ3aWR0aDo3MG1tO2hlaWdodDo1bW07IikKICAgICAgdHIudHJfbm90dm90ZWQKICAg
ICAgICB0ZC5yYW5rICZuYnNwOwogICAgICAgIHRkCiAgICAgICAgCXNwYW4gIXtyZWNvcmQudGFu
bnVtbWVyfQogICAgICB0ci50cl9ub3R2b3RlZAogICAgICAgIHRkLnJhbmsgJm5ic3A7CiAgICAg
ICAgdGQgJm5ic3A7CgkJ') );

SET FOREIGN_KEY_CHECKS=1;