DELIMITER ;
SET FOREIGN_KEY_CHECKS=0;
insert ignore into ds_pug_templates (name,id,note,template) values ('wm_berichte_beteiligung_tagesprokoll_wrapper','wm_berichte_beteiligung_tagesprokoll_wrapper',from_base64('d21fYmVyaWNodGVfYmV0ZWlsaWd1bmdfdGFnZXNwcm9rb2xsX3dyYXBwZXI='),from_base64( 'ZXh0ZW5kcyB3bV9iZXJpY2h0ZV93cmFwcGVyCmJsb2NrIGNvbnRlbnQKICAgIGVhY2ggcmVjb3Jk
IGluIGRhdGEKICAgICAgICAtIHZhciB1c2VkYXRlPXJlY29yZC5kYXR1bQogICAgICAgIGluY2x1
ZGUgd21fYmVyaWNodGVfYmV0ZWlsaWd1bmdfdGFnZXNwcm9rb2xs') );

SET FOREIGN_KEY_CHECKS=1;